if      !def(GENERAL_CHARMAP_INC)
GENERAL_CHARMAP_INC  set  1

; Uppercase
charmap "A", 0
charmap "B", 1
charmap "C", 2
charmap "D", 3
charmap "E", 4
charmap "F", 5
charmap "G", 6
charmap "H", 7
charmap "I", 8
charmap "J", 9
charmap "K", 10
charmap "L", 11
charmap "M", 12
charmap "N", 13
charmap "O", 14
charmap "P", 15
charmap "Q", 16
charmap "R", 17
charmap "S", 18
charmap "T", 19
charmap "U", 20
charmap "V", 21
charmap "W", 22
charmap "X", 23
charmap "Y", 24
charmap "Z", 25

; Lowercase
charmap "a", 36
charmap "b", 37
charmap "c", 38
charmap "d", 39
charmap "e", 40
charmap "f", 41
charmap "g", 42
charmap "h", 43
charmap "i", 44
charmap "j", 45
charmap "k", 46
charmap "l", 47
charmap "m", 48
charmap "n", 49
charmap "o", 50
charmap "p", 51
charmap "q", 52
charmap "r", 53
charmap "s", 54
charmap "t", 55
charmap "u", 56
charmap "v", 57
charmap "w", 58
charmap "x", 59
charmap "y", 60
charmap "z", 61

; Numbers
charmap "0", 26
charmap "1", 27
charmap "2", 28
charmap "3", 29
charmap "4", 30
charmap "5", 31
charmap "6", 32
charmap "7", 33
charmap "8", 34
charmap "9", 35

; Symbols
charmap ".", 62
charmap " ", 63
charmap "!", 64
charmap "“", 65
charmap "”", 66
charmap "#", 67
charmap "$", 68
charmap "%", 69
charmap "&", 70
charmap "‘", 71
charmap "’", 72
charmap "\"", 73
charmap "'", 74
charmap "(", 75
charmap ")", 76
charmap "*", 77
charmap "+", 78
charmap ",", 79
charmap "-", 80
charmap "/", 81
charmap ":", 82
charmap ";", 83
charmap "<", 84
charmap "=", 85
charmap ">", 86
charmap "?", 87
charmap "@", 88
charmap "[", 89
charmap "]", 90
charmap "\\", 91
charmap "^", 92
charmap "_", 93
charmap "■", 94
charmap "|", 95
charmap "\{", 96
charmap "\}", 97
charmap "~", 98

charmap "░", 99

charmap "▒", 100

charmap "▓", 101

charmap "│", 102
charmap "┤", 103
charmap "╣", 104
charmap "║", 105
charmap "╗", 106
charmap "╝", 107
charmap "┐", 108
charmap "└", 109
charmap "┴", 110
charmap "┬", 111
charmap "├", 112
charmap "─", 113
charmap "┼", 114
charmap "╚", 115
charmap "╔", 116
charmap "╩", 117
charmap "╦", 118
charmap "╠", 119
charmap "═", 120
charmap "╬", 121
charmap "┘", 122
charmap "┌", 123
charmap "<█1>", 124
charmap "<█2>", 125
charmap "<█3>", 126
charmap "¦", 127

endc
